import React from 'react'

const Home = () => {
  return (
    <div className='about'>
      <h1 className='home-header'>Welcome to Math Magician</h1>
      <div className='about_body'>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore nulla rem quis optio perspiciatis voluptatibus, totam deserunt porro quas minima. Ipsam facilis nostrum, maxime debitis dolor magnam iste voluptate fugiat aliquid inventore autem, doloremque voluptas sit ad repellendus quia quidem esse eum voluptatibus praesentium provident illum nisi! Sed molestias excepturi aspernatur nisi vel eum aliquam recusandae unde amet sequi laudantium ipsum deserunt vero magni aut provident temporibus quae, ea blanditiis. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae sint blanditiis non, optio numquam ipsam molestias, est magni unde praesentium deserunt alias qui obcaecati fuga dolorum assumenda ad repellendus nisi, repellat maiores nesciunt. Ipsum amet mollitia velit ipsam. Facere odit culpa delectus nulla error placeat neque debitis odio, totam incidunt ut reprehenderit nam omnis cum sint, vel, consequuntur nesciunt eaque maxime amet corrupti aperiam hic? Impedit provident quam quis commodi, consequuntur reiciendis ea, delectus adipisci tempora molestias omnis quasi voluptatibus quisquam. Atque illum voluptatibus earum blanditiis ut repudiandae reiciendis id ea quae suscipit voluptate praesentium optio, cupiditate, cumque architecto quas.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore nulla rem quis optio perspiciatis voluptatibus, totam deserunt porro quas minima. Ipsam facilis nostrum, maxime debitis dolor magnam iste voluptate fugiat aliquid inventore autem, doloremque voluptas sit ad repellendus quia quidem esse eum voluptatibus praesentium provident illum nisi! Sed molestias excepturi aspernatur nisi vel eum aliquam recusandae unde amet sequi laudantium ipsum deserunt vero magni aut provident temporibus quae, ea blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore nulla rem quis optio perspiciatis voluptatibus, totam deserunt porro quas minima. Ipsam facilis nostrum, maxime debitis dolor magnam iste voluptate fugiat aliquid inventore autem, doloremque voluptas sit ad repellendus quia quidem esse eum voluptatibus praesentium provident illum nisi! Sed molestias excepturi aspernatur nisi vel eum aliquam recusandae unde amet sequi laudantium ipsum deserunt vero magni aut provident temporibus quae, ea blanditiis. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae sint blanditiis non, optio numquam ipsam molestias, est magni unde praesentium deserunt alias qui obcaecati fuga dolorum assumenda ad repellendus nisi, repellat maiores nesciunt. Ipsum amet mollitia velit ipsam. Facere odit culpa delectus nulla error placeat neque debitis odio, totam incidunt ut reprehenderit nam omnis cum sint, vel, consequuntur nesciunt eaque maxime amet corrupti aperiam hic? Impedit provident quam quis commodi, consequuntur reiciendis ea, delectus adipisci tempora molestias omnis quasi voluptatibus quisquam. Atque illum voluptatibus earum blanditiis ut repudiandae reiciendis id ea quae suscipit voluptate praesentium optio, cupiditate, cumque architecto quas.</p>
      </div>
    </div>
  )
}

export default Home
